function [fitresult, gof] = fitTriExp(t_ps, p_t)
%CREATEFIT(T_PS,P_T)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t_ps
%      Y Output: p_t
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Apr-2022 20:58:17


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t_ps, p_t );

% Set up fittype and options.
ft = fittype( '(1-b)*((1-a)*exp(-x/tau1)+a*exp(-x/tau2))+b*exp(-x/tau3)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' ,'Robust','Bisquare');
opts.Display = 'Off';
opts.Lower = [0.0 0 0 0 0];
opts.Upper = [1 1 2e3 2e3 4e3 ];
opts.StartPoint = [0.75 0.75 50 50 3e3];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'p_t vs. t_ps', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 't_ps', 'Interpreter', 'none' );
% ylabel( 'p_t', 'Interpreter', 'none' );
% grid on


